global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'opspilot'


rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    
